export const START_REQUEST = 'START_REQUEST'
export const FAILURE_REQUEST = 'FAILURE_REQUEST'
export const SUCCESS_REQUEST = 'SUCCESS_REQUEST'
export const CLEAN_MESSAGE_REQUEST = 'CLEAN_MESSAGE_REQUEST'
